server:
  port: 8082

spring:
  application:
    name: storage-service
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: ${JWT_SECRET:YWUzZjM4NWQ2NWFiNGI0MmFmMWJjZDI4NDBlOGZiMmExMTA2ZDI5NWIwODI2NjdmYzIyOWI1YTRmNzkyYTQwMQ==}

logging:
  service:
    host: ${UDP_LOG_HOST:localhost}
    port: 9000
